version: '3.8'

services:
  api:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/widgetdb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: